version: "3.8"

volumes:
  db_volume_data:
    driver: local

networks:
  my_links_net:
    name: my_links_net

services:
  my-links-db:
    image: mysql:latest
    restart: always
    volumes:
      - db_volume_data:/var/lib/postgresql/data
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    networks:
      - my_links_net

  my-links:
    image: sonny/my-links:latest
    container_name: MyLinks
    ports:
      - 3000:3000
    restart: always
    environment:
      DATABASE_URL: "mysql://${DB_USER}:${DB_PASSWORD}@my-links-db:3306/${DB_DATABASE}"
    depends_on:
      my-links-db:
        condition: service_started
    networks:
      - my_links_net
